# Generated by Django 2.2.2 on 2019-07-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=200)),
                ('place_name', models.CharField(max_length=200)),
                ('place_location', models.CharField(max_length=200)),
                ('reader', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('game_type', models.CharField(max_length=200)),
                ('metro', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=200)),
            ],
        ),
    ]
