# Generated by Django 3.0.7 on 2020-06-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwich', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
