# Generated by Django 3.0.2 on 2020-01-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwich', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='place_lat',
            field=models.DecimalField(decimal_places=5, default=55.755814, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='place_long',
            field=models.DecimalField(decimal_places=5, default=37.617635, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='organizer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
