# Generated by Django 3.0.2 on 2020-01-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwich', '0002_auto_20200105_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='place_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='place_long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
